version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15.4-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - data:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always

volumes:
  data:
   
